export const PERMISSIONS = {
  PROPERTIES_VIEW:    'properties:view',
  PROPERTIES_CREATE:  'properties:create',
  PROPERTIES_EDIT:    'properties:edit',
  PROPERTIES_DELETE:  'properties:delete',
  TENANTS_VIEW:       'tenants:view',
  TENANTS_CREATE:     'tenants:create',
  TENANTS_EDIT:       'tenants:edit',
  LEASES_VIEW:        'leases:view',
  LEASES_CREATE:      'leases:create',
  LEASES_EDIT:        'leases:edit',
  PAYMENTS_VIEW:      'payments:view',
  PAYMENTS_CREATE:    'payments:create',
  PAYMENTS_REFUND:    'payments:refund',
  MAINTENANCE_VIEW:   'maintenance:view',
  MAINTENANCE_CREATE: 'maintenance:create',
  MAINTENANCE_ASSIGN: 'maintenance:assign',
  ACCOUNTING_VIEW:    'accounting:view',
  ACCOUNTING_EDIT:    'accounting:edit',
  REPORTS_VIEW:       'reports:view',
  REPORTS_EXPORT:     'reports:export',
  SETTINGS_VIEW:      'settings:view',
  SETTINGS_EDIT:      'settings:edit',
  USERS_MANAGE:       'users:manage',
}
